title: GUIMath
description: Create mathematical equations on webpages using a GUI
theme: just-the-docs

url: https://hrushikeshrv.github.io/guimath

aux_links:
  "View on GitHub": https://github.com/hrushikeshrv/guimath

enable_copy_code_button: true

callouts:
  important:
    title: Important
    color: red
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: purple

ga_tracking: G-TGM5F6WJNV

nav_external_links:
  - title: View on GitHub
    url: https://github.com/hrushikeshrv/guimath
    opens_in_new_tab: true
  - title: Raise an Issue
    url: https://github.com/hrushikeshrv/guimath/issues
    opens_in_new_tab: true

favicon_ico: "/media/favicon.png"